---
name: "Build AI models"
description: "Build AI models and repackage them with Flux OCI"
author: "Chanwit Kaewkasi"
inputs:
  repository:
    required: true
  filename:
    required: true
  image:
    required: true
  ghcrToken:
    required: true
runs:
  using: composite
  steps:
  - name: Set up Python 3.10
    uses: actions/setup-python@v2
    with:
      python-version: "3.10"
  - name: Setup Flux CLI
    uses: fluxcd/flux2/action@main
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install huggingface_hub
      apt-get install tree
  - name: Download model
    env:
      MODEL_REPO: ${{ inputs.repository }}
      MODEL_FILE: ${{ inputs.filename }}
    run: |
      python download.py

      rm -rf model || true
      mkdir model
      cd model

      MODEL_DIR=$PWD
      pushd .
      tree .
      TARGET=$(readlink ${{ inputs.filename }})
      cd $(dirname ${{ inputs.filename }})
      cp --remove-destination $TARGET $(basename ${{ inputs.filename }})
      popd
      rm -rf $TARGET

      # flatten structure
      find . -mindepth 2 -type f | while read -r file; do
          # Move each file to the /models directory
          mv "$file" "${MODEL_DIR}/$(basename "$file")"
      done
      # once all files have been moved, find and remove any empty directories
      find . -type d -empty -delete
  - name: Push model
    run: |
      cd model
      tree .
      flux push artifact \
        --creds chanwit:${{ inputs.ghcrToken }} \
        oci://ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ inputs.image }} \
        --timeout 120m0s \
        --path="./" \
        --source="$(git config --get remote.origin.url)" \
        --revision="$(git branch --show-current)@sha1:$(git rev-parse HEAD)"    

branding:
  icon: 'code'
  color: 'yellow'
